// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240708131145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Age = 30,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9709),
                            DateOfBirth = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "124 Main St",
                            Age = 28,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9727),
                            DateOfBirth = new DateTime(1995, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7891",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "125 Main St",
                            Age = 35,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9729),
                            DateOfBirth = new DateTime(1988, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            Gender = "Female",
                            LastName = "Smith",
                            PhoneNumber = "123-456-7892",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "126 Main St",
                            Age = 40,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9733),
                            DateOfBirth = new DateTime(1983, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.smith@example.com",
                            FirstName = "Bob",
                            Gender = "Male",
                            LastName = "Smith",
                            PhoneNumber = "123-456-7893",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "127 Main St",
                            Age = 25,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9735),
                            DateOfBirth = new DateTime(1998, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie.brown@example.com",
                            FirstName = "Charlie",
                            Gender = "Male",
                            LastName = "Brown",
                            PhoneNumber = "123-456-7894",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "128 Main St",
                            Age = 45,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9736),
                            DateOfBirth = new DateTime(1978, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.johnson@example.com",
                            FirstName = "David",
                            Gender = "Male",
                            LastName = "Johnson",
                            PhoneNumber = "123-456-7895",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "129 Main St",
                            Age = 32,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9738),
                            DateOfBirth = new DateTime(1991, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.johnson@example.com",
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Johnson",
                            PhoneNumber = "123-456-7896",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "130 Main St",
                            Age = 50,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9740),
                            DateOfBirth = new DateTime(1973, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank.miller@example.com",
                            FirstName = "Frank",
                            Gender = "Male",
                            LastName = "Miller",
                            PhoneNumber = "123-456-7897",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "131 Main St",
                            Age = 37,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9742),
                            DateOfBirth = new DateTime(1986, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.miller@example.com",
                            FirstName = "Grace",
                            Gender = "Female",
                            LastName = "Miller",
                            PhoneNumber = "123-456-7898",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "132 Main St",
                            Age = 55,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9749),
                            DateOfBirth = new DateTime(1968, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.adams@example.com",
                            FirstName = "Henry",
                            Gender = "Male",
                            LastName = "Adams",
                            PhoneNumber = "123-456-7899",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Address = "133 Main St",
                            Age = 27,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9751),
                            DateOfBirth = new DateTime(1996, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.adams@example.com",
                            FirstName = "Isabella",
                            Gender = "Female",
                            LastName = "Adams",
                            PhoneNumber = "123-456-7900",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Address = "134 Main St",
                            Age = 38,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9753),
                            DateOfBirth = new DateTime(1985, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack.wilson@example.com",
                            FirstName = "Jack",
                            Gender = "Male",
                            LastName = "Wilson",
                            PhoneNumber = "123-456-7901",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Address = "135 Main St",
                            Age = 42,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9755),
                            DateOfBirth = new DateTime(1981, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karen.wilson@example.com",
                            FirstName = "Karen",
                            Gender = "Female",
                            LastName = "Wilson",
                            PhoneNumber = "123-456-7902",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Address = "136 Main St",
                            Age = 33,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9756),
                            DateOfBirth = new DateTime(1990, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "larry.martinez@example.com",
                            FirstName = "Larry",
                            Gender = "Male",
                            LastName = "Martinez",
                            PhoneNumber = "123-456-7903",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Address = "137 Main St",
                            Age = 29,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9758),
                            DateOfBirth = new DateTime(1994, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "megan.martinez@example.com",
                            FirstName = "Megan",
                            Gender = "Female",
                            LastName = "Martinez",
                            PhoneNumber = "123-456-7904",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Address = "138 Main St",
                            Age = 46,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9760),
                            DateOfBirth = new DateTime(1977, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nancy.garcia@example.com",
                            FirstName = "Nancy",
                            Gender = "Female",
                            LastName = "Garcia",
                            PhoneNumber = "123-456-7905",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Address = "139 Main St",
                            Age = 52,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9762),
                            DateOfBirth = new DateTime(1971, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.garcia@example.com",
                            FirstName = "Oscar",
                            Gender = "Male",
                            LastName = "Garcia",
                            PhoneNumber = "123-456-7906",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Address = "140 Main St",
                            Age = 31,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9763),
                            DateOfBirth = new DateTime(1992, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.rodriguez@example.com",
                            FirstName = "Patricia",
                            Gender = "Female",
                            LastName = "Rodriguez",
                            PhoneNumber = "123-456-7907",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            Address = "141 Main St",
                            Age = 27,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9765),
                            DateOfBirth = new DateTime(1996, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quentin.clark@example.com",
                            FirstName = "Quentin",
                            Gender = "Male",
                            LastName = "Clark",
                            PhoneNumber = "123-456-7908",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Address = "142 Main St",
                            Age = 35,
                            CreatedDate = new DateTime(2024, 7, 8, 16, 11, 44, 756, DateTimeKind.Local).AddTicks(9767),
                            DateOfBirth = new DateTime(1988, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rachel.clark@example.com",
                            FirstName = "Rachel",
                            Gender = "Female",
                            LastName = "Clark",
                            PhoneNumber = "123-456-7909",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
